config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :products, except: [:destroy] do
      resources :rate_plans, except: [:destroy]
    end
  end

  namespace :api do
    resources :products, only: [:index, :show]
  end

  root 'admin/products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  include ActiveModel::Dirty
  validates :start_date, presence: true
  validates :title, presence: true
  validates :status, presence: true

  has_many :rate_plans
  before_save :sync_fields

  class Status
    ACTIVE = 'active'
    DISCONTINUED = 'discontinued'
    ALL_STATUSES = [ACTIVE, DISCONTINUED]
  end

  def self.editable_fields
    %I(title description start_date end_date status)
  end

  def sync_fields
    if end_date_changed?
      discontinued = !end_date.nil? && (end_date < DateTime.now)
      self.status = discontinued ? Status::DISCONTINUED : Status::ACTIVE
    elsif status_changed?
      case status
      when Status::ACTIVE
        self.end_date = nil
      when Status::DISCONTINUED
        self.end_date = DateTime.now
      end
    end
  end
end

app/models/rate_plan.rb
class RatePlan < ActiveRecord::Base
  include ActiveModel::Dirty
  validates :title, presence: true
  validates :status, presence: true
  validates :recurrence, presence: true
  validates :price, presence: true
  validates :start_date, presence: true

  belongs_to :product

  before_save :sync_fields

  enum recurrence: { one_time: 0, monthly: 1, quarterly: 2, annually: 3 }

  class Status
    ACTIVE = 'active'
    RETIRED = 'retired'
    ALL_STATUSES = [ACTIVE, RETIRED]
  end

  def self.editable_fields
    %I[title description start_date end_date product_id recurrence price status]
  end

  def sync_fields
    if end_date_changed?
      retired = !end_date.nil? && (end_date < DateTime.now)
      self.status = retired ? Status::RETIRED : Status::ACTIVE
    elsif status_changed?
      case status
      when Status::ACTIVE
        self.end_date = nil
      when Status::RETIRED
        self.end_date = DateTime.now
      end
    end
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < ApplicationController
    def index
      @filters = params[:status] ? { status: params[:status].downcase.to_sym } : {}
      @products = ProductManager.all(@filters)
    end

    def new
      @product = ProductManager.new(start_date: DateTime.now)
    end

    def create
      permitted = params.require(:product).permit(ProductManager.permitted_values)
      created, data = ProductManager.create(permitted)
      if created
        flash[:notice] = 'Product Created'
        redirect_to admin_products_path
      else
        @product = data[:errors][:model]
        listed_error_message = @product.errors.full_messages.join('\n')
        flash[:error] = "Product Creation Error:\n #{listed_error_message}"
        render :new
      end
    end

    def show
      @product = ProductManager.find(params[:id])
    end

    def edit
      @product = ProductManager.find(params[:id])
    end

    def update
      permitted = params.require(:product).permit(ProductManager.permitted_values)
      updated, data = ProductManager.update(params[:id], permitted)

      if updated
        flash[:notice] = 'Product Updated'
        redirect_to admin_product_path(params[:id])
      else
        @product = data[:errors][:model]
        listed_error_message = @product.errors.full_messages.join('/\n')
        flash[:error] = "Product Update Error:\n #{listed_error_message}"
        render :edit
      end
    end
  end
end

app/controllers/admin/rate_plans_controller.rb
module Admin
  class RatePlansController < ApplicationController
    def index
      permitted = params.permit([:status, :product_id])

      filter_keys = [:status, :product_id]
      data_filters = permitted.slice(*filter_keys)
      @rate_plans = RatePlanManager.all(data_filters)
      @product = ProductManager.find(permitted[:product_id])
      @presentation_filters = data_filters.except(:product_id)
    end

    def new
      @product = ProductManager.find(params['product_id'])
      @rate_plan = RatePlanManager.new(product_id: @product.id, start_date: DateTime.now)
    end

    def create
      permitted = params.require(:rate_plan).permit(RatePlanManager.permitted_values)
      created, data = RatePlanManager.create(permitted)
      if created
        flash[:notice] = 'Rate Plan Created'
        redirect_to admin_product_rate_plans_path(permitted[:product_id])
      else
        @rate_plan = data[:errors][:model]
        @product = ProductManager.find(params[:product_id])
        listed_error_message = @rate_plan.errors.full_messages.join('\n')
        flash[:error] = "Rate Plan Creation Error:\n #{listed_error_message}"
        render :new
      end
    end

    def show
      @rate_plan = RatePlanManager.find(params[:id])
      @product = ProductManager.find(@rate_plan.product_id)
    end

    def edit
      @rate_plan = RatePlanManager.find(params[:id])
    end

    def update
      permitted = params.require(:rate_plan).permit(RatePlanManager.permitted_values)
      updated, data = RatePlanManager.update(params[:id], permitted)
      if updated
        flash[:notice] = 'Rate Plan Updated'
        redirect_to admin_product_rate_plan_path(params[:id])
      else
        @rate_plan = data[:errors][:model]
        @product = ProductManager.find(params[:product_id])
        listed_error_message = @rate_plan.errors.full_messages.join('/\n')
        flash[:error] = "Rate Plan Update Error:\n #{listed_error_message}"
        render :edit
      end
    end
  end
end

app/controllers/api/products_controller.rb
module Api
  class ProductsController < ApplicationController
    def index
      products = ProductManager.all(status: Product::Status::ACTIVE)
      render json: products
    end

    def show
      product = ProductManager.find(params[:id])
      rate_plans = RatePlan.where(product_id: params[:id], status: RatePlan::Status::ACTIVE)
      if product
        product_data = product.as_json
        product_data['rate_plans'] = rate_plans.as_json
        render json: product_data
      else
        render json: { error: 'Product Not Found' }
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_datetime(datetime_object)
    return unless datetime_object
    datetime_object.strftime('%m/%d/%Y')
  end
end

app/views/admin/products/edit.html.erb
<h1>Edit Product</h1>

<div class="navbar">
  <%= link_to('Back To Product Details', admin_product_path(@product), class: "btn btn-secondary") %>
</div>
<div class="col-sm-6">
<%= form_for @product, url: admin_product_path  do |f| %>
  <div class="form-group">
    <%= label_tag 'Title' %>
    <%= f.text_field :title, class: 'form-control', maxLength: 60 %>
  </div>
  <div class="form-group">
    <%= label_tag 'Description' %>
    <%= f.text_area :description, class: 'form-control', rows: 3 %></div>
  <div class="form-group">
    <%= label_tag 'Status' %>
    <%= f.select(:status, options_for_select(Product::Status::ALL_STATUSES, @product.status)) %>
  </div>
  <div class="form-group">
    <%= label_tag 'Start Date' %>
    <%= f.date_field :start_date, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= label_tag 'End Date' %>
    <%= f.date_field :end_date, class: 'form-control' %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>
</div>

app/views/admin/products/index.html.erb
<h2>Products</h2>

<div class="navbar">
  <%=link_to "Add New Product", new_admin_product_path, class: "btn btn-primary" %>
  <div class="float-right">
    <% if @filters.empty? %>
      <%= link_to('only active', admin_products_path(status: Product::Status::ACTIVE), class: "btn btn-secondary") %>
    <% else %>
      <%= link_to('clear filters', admin_products_path, class: "btn btn-dark") %>
    <% end %>
  </div>
</div>
<table class="table table-hover">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Status</th>
  </tr>
  <% @products.each do |product| %>
    <tr>
      <td><%= link_to product.title, admin_product_path(product) %></td>
      <td><%= product.description %></td>
      <td><%= product.status.humanize %></td>
    </tr>
  <% end %>
</table>
</div>

app/views/admin/products/new.html.erb
<h1>New Product</h1>

<div class="col-sm-7">
  <div class="navbar">
    <div><%= link_to('Back To All Products', admin_products_path, class: 'btn btn-secondary') %></div>
  </div>
  <div class="form">
  <%= form_for @product, url: admin_products_path do |f| %>
    <div class="form-group">
      <%= label_tag 'Title' %>
      <%= f.text_field :title, class: 'form-control', maxLength: 60 %>
    </div>
    <div class="form-group">
      <%= label_tag 'Description' %>
      <%= f.text_area :description, class: 'form-control', rows: 3 %>
    </div>
    <div class="form-group">
      <%= label_tag 'Status' %>
      <%= f.select :status, options_for_select(Product::Status::ALL_STATUSES, default: Product::Status::ACTIVE) %>
    </div>
    <div class="form-group">
      <%= label_tag 'Start Date' %>
      <%= f.date_field :start_date, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag 'End Date' %>
      <%= f.date_field :end_date, class: 'form-control' %>
    </div>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/admin/products/show.html.erb
<h1>Product Details</h1>

<div class="col-sm-7">
  <div class="navbar">
    <div><%= link_to 'Back To All Products', admin_products_path, class: "btn btn-secondary" %></div>
    <div><%= link_to 'Edit Product', edit_admin_product_path(@product), class: "btn btn-primary" %></div>
    <div><%= link_to('Rate Plans', admin_product_rate_plans_path(product_id: @product.id), class: "btn btn-info") %></div>
  </div>

  <form class="form">
    <div class="form-group">
      <%= label(:title, "Title:") %>
      <div class="form-control"><%= @product.title %></div>
    </div>
    <div class="form-group">
      <%= label(:description, "Description:") %>
      <div class="form-control"><%= @product.description %></div>
    </div>
    <div class="form-group">
      <%= label(:start_date, "Start Date") %>
      <div class="form-control"><%= format_datetime(@product.start_date) %></div>
    </div>
    <div class="form-group">
      <%= label(:start_date, "End Date") %>
      <div class="form-control"><%= format_datetime(@product.end_date) || 'N/A' %></div>
    </div>
    <div class="form-group">
      <%= label(:status, "Status:") %>
      <div class="form-control"><%= @product.status.humanize %></div>
    </div>
    <div class="form-group">
    </div>
  </form>
</div>

app/views/admin/rate_plans/edit.html.erb
<h1>Edit Rate Plan</h1>

<div class="col-sm-7">
  <div class="navbar">
     <div><%= link_to('Back To Rate Plan Details', admin_product_rate_plan_path(@rate_plan), class: "btn btn-secondary") %></div>
  </div>

  <div>
    <%= form_for @rate_plan, url: admin_product_rate_plan_path do |f| %>
    <div class="form-group">
      <%= label_tag 'Title' %>
      <%= f.text_field :title, class: 'form-control', maxLength: 60 %>
    </div>
    <div class="form-group">
      <%= label_tag 'Description' %>
      <%= f.text_area :description, class: 'form-control', rows: 3 %>
    </div>
    <div class="form-group">
      <%= label_tag 'Status' %>
      <%= f.select :status, options_for_select(RatePlan::Status::ALL_STATUSES, @rate_plan.status) %>
    </div>
    <div class="form-group">
      <%= label_tag 'Recurrence' %>
      <%= f.select :recurrence, options_for_select(RatePlan.recurrences.keys, @rate_plan.recurrence) %>
    </div>
    <div class="form-group">
      <%= label_tag 'Price' %>
      <%= f.text_field :price %>
    </div>
    <div class="form-group">
      <%= label_tag 'Start Date' %>
      <%= f.date_field :start_date, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag 'End Date' %>
      <%= f.date_field :end_date, class: 'form-control' %>
    </div>
    <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/admin/rate_plans/index.html.erb
<h1>Rate Plans For <%= @product.title %></h1>

<div class="col-sm-7">
  <div class="navbar">
    <div><%= link_to("Back To #{@product.title}", admin_product_path(@product), class: 'btn btn-info' ) %></div>
    <div><%= link_to('Add New Rate Plan', new_admin_product_rate_plan_path(@product), class: 'btn btn-primary') %></div>
    <div>
      <% if @presentation_filters.empty? %>
        <%= link_to('only active', admin_product_rate_plans_path(status: Product::Status::ACTIVE, product_id: @product.id), class: 'btn btn-secondary float-right') %>
      <% else %>
        <%= link_to('clear filters', admin_product_rate_plans_path(@product), class: 'btn btn-dark float-right') %>
      <% end %>
    </div>
  </div>
</div>


<table class="table table-hover">
  <tr>
    <th>Title</th>
    <th>Status</th>
    <th>Recurrence</th>
    <th>Price</th>
    <th>Description</th>
  </tr>
  <% @rate_plans.each do |rate_plan| %>
    <tr>
      <td><%= link_to(rate_plan.title, admin_product_rate_plan_path(@product.id, rate_plan.id)) %></td>
      <td><%= rate_plan.status.capitalize %></td>
      <td><%= rate_plan.recurrence %></td>
      <td><%= rate_plan.price %></td>
      <td><%= rate_plan.description %></td>
    </tr>
  <% end %>
</table>

app/views/admin/rate_plans/new.html.erb
<h1>New Rate Plan</h1>

<div class="col-sm-7">
  <div class="navbar">
    <div><%= link_to("Back to Rate Plans", admin_product_rate_plans_path(@product), class: 'btn btn-secondary') %></div>
  </div>
<div class="container">
  <%= form_for @rate_plan, url: admin_product_rate_plans_path do |f| %>
    <div class="form-group">
      <%= label_tag :product_id, 'Product ID' %>
      <%= f.text_field :product_id, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag 'Title' %>
      <%= f.text_field :title, class: 'form-control', maxLength: 60 %>
    </div>
    <div class="form-group">
      <%= label_tag 'Description' %>
      <%= f.text_area :description, class: 'form-control', rows: 3 %>
    </div>
    <div class="form-group">
      <%= label_tag 'Status' %>
      <%= f.select :status, options_for_select(RatePlan::Status::ALL_STATUSES, default: RatePlan::Status::ACTIVE) %>
    </div>
    <div class="form-group">
      <%= label_tag 'Recurrence' %>
      <%= f.select :recurrence, options_for_select(RatePlan.recurrences.keys) %>
    </div>
    <div class="form-group">
      <%= label_tag 'Price' %>
      <%= f.text_field :price, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag 'Start Date' %>
      <%= f.date_field :start_date, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag 'End Date' %>
      <%= f.date_field :end_date, class: 'form-control' %>
    </div>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/admin/rate_plans/show.html.erb
<h1>Rate Plan Details</h1>
<div class="col-sm-7">
  <div class="navbar">
    <div><%= link_to 'Back To Rate Plans', admin_product_rate_plans_path(@product), class: 'btn btn-secondary' %></div>
    <div><%= link_to 'Edit Rate Plan', edit_admin_product_rate_plan_path(@rate_plan), class: 'btn btn-primary' %></div>
  </div>
  <form class="form">
    <div class="form-group">
       <%= label_tag 'Title' %>
       <div class="form-control"><%= @rate_plan.title %></div>
    </div>
    <div class="form-group">
      <div><%= label_tag 'Description:' %></div>
      <%= @rate_plan.description %>
    </div>
    <div class="form-group">
      <%= label_tag 'Status' %>
      <div class="form-control"><%= @rate_plan.status %></div>
    </div>
    <div class="form-group">
      <%= label_tag 'Recurrence' %>
      <div class="form-control"><%= @rate_plan.recurrence %></div>
    </div>
    <div class="form-group">
      <%= label_tag 'Price' %>
      <div class="form-control"><%= @rate_plan.price %></div>
    </div>
    <div class="form-group">
      <%= label_tag 'Start Date' %>
      <div class="form-control"><%= format_datetime(@rate_plan.start_date) || 'N/A' %></div>
    </div>
    <div class="form-group">
      <%= label_tag 'End Date' %>
      <div class="form-control"><%= format_datetime(@rate_plan.end_date) || 'N/A' %></div>
    </div>
  </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BigCommerce</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <% if flash[:notice] %>
        <p class="alert alert-success"><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:error] -%>
        <p class="alert alert-danger"><%= flash[:error] %></p>
      <% end %>
    </div>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>